### ISSUE TITLE
the function "scale_fill_manual" need library the ggplot2 packages 

### ISSUE THREAD

**Issue by wangjiaxuan666** [YuLab-SMU/ggtree#277]
### Describe you issue

I am your fans , when I use the ggtree today, I find a question, not import.
maybe you have solved the problem,but I haved used function`update.packages("ggtree")` update the packages form cran.  

but the probelm didn't disappear. So I came to to github. 

**my code : **

```{r}
require(ape)
require(ggtree)
write.tree(as.phylo(hclust(dist(mtcars))),file = "my_tree.nwk")
inname <- "my_tree.nwk"
tree <- read.tree(inname)
ggtree(tree,color="black", size=1.5, linetype=1,right=TRUE) + 
  geom_tiplab(size=4.5, hjust = -0.060, fontface="bold") +
  geom_treescale() +
  geom_point(aes(shape=isTip, color = isTip,fill=isTip), shape=21, size=4)+
  theme_tree(legend.position=c(0.1, 0.2)) +
  scale_fill_manual(values=c("white", "black"))+
  scale_color_manual(values=c("white", "black"))
```

and the wrong message is "Error in scale_fill_manual(values = c("white", "black")) : 
  could not find function "scale_fill_manual"

if I add the `ggplot2::` before the `scale_color_manual`,  it can run correctly. just like `ggplot2::scale_color_manual` . the problem disappear. 

Thank you for providing the wonderful packages again.

**Comment by brj1** [comment]
You can put `library(ggplot2)` at the beginning of your code to get around having to put `ggplot2::` infront of ggplot2 functions.

Also `update.packages("ggtree")` does not work, because ggtree is not on CRAN. To install ggtree, the proper method is to use Bioconductor. 

```
install.packages("BiocManager")
BiocManager::install("ggtree")
```

As a final a final note, I don't think that this request will (or should) be implemented because then Guangchuang would have to this for EVERY `ggplot2` function, which is not practical and may mess up the packages hierarchy.

**Comment by brj1** [comment]
This has been implemented in the dev version.

```R
install.pavcages("devtools")
devtools::install_github("YuLab-SMU/ggtree")
```

Also ggtree is not on CRAN and `update.packages("ggtree")` should fail (unless there some way to link Biocounductor to `update.packages`).
