### ISSUE TITLE
cant combine ggtree with nodepie inset and geological bars from deeptime

### ISSUE THREAD

**Issue by oscarIM** [YuLab-SMU/ggtree#419]
I am trying to combine a ggtree with node pie inset with geologic bars from the deeptime package. For this, I first create the tree with the nodepie and then add the geological bars. This gives the error : Error: annotation_custom only works with Cartesian coordinates (above minimal example): 
```library(geiger)
library(ape)
library(phytools)
library(ggtree)
library(deeptime)
set.seed(12345)
tree <- sim.bdtree(b = 0.1, d = 0, stop = "time", t = 20, seed = 12345)
#sim trait
trait <- rTraitDisc(tree)
trait_anc <- data.frame(rerootingMethod(tree, trait)$marginal.anc)
trait_anc$node <- row.names(trait_anc)
#tree with pie
p <- ggtree(tree)
pies <- nodepie(trait_anc, cols = 1:2, color = c("darkorange1","blue"), alpha = 0.8)
p_pie <- inset(p, pies, width = 0.07, height = 0.07)
#tree with pie
p_pie_time <- p_pie +  coord_geo()#just default`

**Comment by xiangpin** [comment]
This is because the `annotation_custom` of `ggplot2` is not compatible with the other `coord`. However, you can use `geom_plot` of [`ggpp`](https://github.com/aphalo/ggpp) to display the example. You can refer to the following codes.

```
> library(ape)
> library(phytools)
Loading required package: maps
> library(ggtree)
ggtree v3.1.2  For help: https://yulab-smu.top/treedata-book/

If you use ggtree in published research, please cite the most appropriate paper(s):

1. Guangchuang Yu. Using ggtree to visualize data on tree-like structures. Current Protocols in Bioinformatics, 2020, 69:e96. doi:10.1002/cpbi.96
2. Guangchuang Yu, Tommy Tsan-Yuk Lam, Huachen Zhu, Yi Guan. Two methods for mapping and visualizing associated data on phylogeny using ggtree. Molecular Biology and Evolution 2018, 35(12):3041-3043. doi:10.1093/molbev/msy194
3. Guangchuang Yu, David Smith, Huachen Zhu, Yi Guan, Tommy Tsan-Yuk Lam. ggtree: an R package for visualization and annotation of phylogenetic trees with their covariates and other associated data. Methods in Ecology and Evolution 2017, 8(1):28-36. doi:10.1111/2041-210X.12628


> library(deeptime)
> library(geiger)
> set.seed(12345)
> tree <- sim.bdtree(b = 0.1, d = 0, stop = "time", t = 20, seed = 12345)
> trait <- rTraitDisc(tree)
> trait_anc <- data.frame(rerootingMethod(tree, trait)$marginal.anc)
> trait_anc$node <- row.names(trait_anc)
> pies <- nodepie(trait_anc, cols = 1:2, color = c("darkorange1","blue"), alpha = 0.8)
> df <- tibble::tibble(node=as.numeric(trait_anc$node), pies=pies)
> p1 <- ggtree(tree)
> p2 <- p1 %<+% df
> library(ggpp)
Loading required package: ggplot2
> p2 + geom_plot(data=td_filter(!isTip), mapping=aes(x=x,y=y, label=pies), vp.width=0.09, vp.height=0.09, hjust=0.5, vjust=0.5) + coord_geo()
```
![ggpies](https://user-images.githubusercontent.com/17870644/125151695-93640f00-e17a-11eb-94d3-a9c7ec393fa0.PNG)

**Comment by oscarIM** [comment]
thank you very much for your help!
Best

**Comment by bastianheimburger** [comment]
Hi,

I just realized that `geom_plot` switches the position of node pies.
![github](https://user-images.githubusercontent.com/25033123/137274690-2b004f46-1c52-4091-813a-a5e0fa9994ca.png)
 
For the left plot I simply used `> plot(objER,ftype="i",fsize=0.9, colors=cols)`. Ancestral states have been inferred with `phytools`.

The right plot is using `geom_plot` as following:

```
> p <- ggtree(input.tre, right = T)
> ancstats <- as.data.frame(objER$ace)
> ancstats$node <- row.names(ancstats)
> pies <- nodepie(ancstats, cols = 1:3, color = c("#a52a2aff","#5a5a5aff","#ff7b00ff"))
> df <- tibble::tibble(node=as.numeric(ancstats$node), pies=pies)
> p1 <- p %<+% df
> p1 + geom_plot(data=td_filter(!isTip), mapping=aes(x=x,y=y, label=pies), vp.width=0.09, vp.height=0.09, hjust=0.5, vjust=0.5)
```
I hope you can help,

Bastian

**Comment by bioyear** [comment]
Thanks for this question and kindly reply, I have got a lot help from that. But it comes a new question that when I figured out two traits in a single tree plot, in other words when I use `geom_plot` twice, the second pie layer didn't work. So, how can I deal this question?
Thank you again!

**Comment by warrenlr** [comment]
Thank you for this.  I am able to plot pies at each leaf of a circular tree, but only when the branch lengths are set. This works:
`library(ggtree)
library(dplyr)

# Read the population data
pop <- read.table("simonsuniqueGAIfromLAI.tsv", header = TRUE, sep = "\t")


# Read the Newick tree from file
tree <- read.tree("fixmergedbest.vcf.nj.nwk")

# Define colors for each region
region_colors <- c(
  "Africa" = "orange",
  "America" = "black",
  "CentralAsiaSiberia" = "purple",
  "EastAsia" = "red",
  "Oceania" = "#fa9fb5",
  "SouthAsia" = "#0080FF",
  "WestEurasia" = "#2ca25f"
)  


pop_join <- inner_join(x = as.data.frame(fortify(tree)), y = pop %>% mutate(label=ID), by=c("label"))
pies <- nodepie(pop_join, cols = 19:23, color = c("orange","black","red", "green", "blue"), alpha=0.75)
                                                  

p <- ggtree(tree, layout="circular", aes(color=Region)) %<+% pop +
  #geom_tippoint(aes(color = Region), size=2.5) +
  geom_tiplab(aes(label = popID, color = Region), align=TRUE, size = 2.75,  offset = 0.001, hjust = 0, vjust=0, linetype='dotted', linesize=0.2) + # removed align=TRUE,
  scale_color_manual(values = region_colors) +
  geom_treescale(x = 0.12)

library(ggpp)
p <- p + geom_plot(data=pop_join, mapping=aes(x=x,y=y, label=pies), vp.width=0.015, vp.height=0.015, hjust=0.5, vjust=0.5) 

print(p)`

BUT, when I set the branch length to None, the pies are all plotted in the center, and on top of each other.

`p <- ggtree(tree, layout="circular", branch.length = 'none') %<+% pop_join +`

 If anything, mapping the pies to each leaf should be an easier problem since they are all equidistant from the center.

Do you have any hints on how to fix?
