### ISSUE TITLE
geom_tree produces tree with different layout than was set earlier with ggtree

### ISSUE THREAD

**Issue by TuomasBorman** [YuLab-SMU/ggtree#424]
Hi,

we found a possible bug from `ggtree`. 

`geom_tree` produces tree with different layout than was set earlier with `ggtree`. 

Example below demonstrates the issue. tree object can be found from the `tree.zip` file:

```
library(ggtree)
tree <- readRDS("tree")
plot_out <- ggtree(tree,layout = "ellipse")
plot_out
```
![image](https://user-images.githubusercontent.com/60338854/127708599-50aad9fd-16ed-4a53-806f-d8904a9c1b84.png)

`plot_out + geom_tree()`
![image](https://user-images.githubusercontent.com/60338854/127708670-a1f781a2-3a46-4439-af2e-8a375f7f6fbd.png)
[tree.zip](https://github.com/YuLab-SMU/ggtree/files/6909893/tree.zip)

BR,
Tuomas Borman

**Comment by brj1** [comment]
This is not a bug. `ggtree(tree)` is in some ways short for `ggplot(tree) + geom_tree()`. The `layout` parameter is a parameter of the `geom_tree` function and applies to the specific `geom_tree` layer. Because of this, the `layout` parameter is not passed to subsequently added `geom_tree` layers added to the plot. You can get `geom_tree` to plot the new tree with the same layout by adding a `layout` parameter to the `geom_tree` call.

**Comment by GuangchuangYu** [comment]
the `layout` parameter is not inherited.  see also <http://yulab-smu.top/treedata-book/chapter2.html#ggtree-fortify>

**Comment by TuomasBorman** [comment]
Alright, thanks for your answers!
-Tuomas
